spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

