name: orderease
description: "A mobile terminal for easily manage business(orders, payments) of any company."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_easyloading: ^3.0.5

  http: ^0.13.3

  provider: ^6.0.1

  intl: ^0.18.1

  awesome_snackbar_content: 0.1.1

  lottie: ^1.0.1

  shimmer: ^2.0.0

  shared_preferences: ^2.2.0

  flutter_spinkit: ^5.2.0

  awesome_dialog: ^3.1.0

  restart_app: ^1.2.1

  flat_3d_button: ^1.0.3

  carousel_slider: ^4.2.1

  google_nav_bar: ^5.0.6

  curved_navigation_bar: ^1.0.3

  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
  adaptive_icon_background: "#132a3a"
  adaptive_icon_foreground: "assets/images/logo_app.png"
  min_sdk_android: 22


flutter:

  
  uses-material-design: true



  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/animations/
  

  fonts:
    - family: PetrovSans
      fonts:
        - asset: assets/fonts/PetrovSans-Black.ttf
        - asset: assets/fonts/PetrovSans-BlackItalic.ttf
        - asset: assets/fonts/PetrovSans-Bold.ttf
        - asset: assets/fonts/PetrovSans-BoldItalic.ttf
        - asset: assets/fonts/PetrovSans-Book.ttf
        - asset: assets/fonts/PetrovSans-BookItalic.ttf
        - asset: assets/fonts/PetrovSans-ExtraBold.ttf
        - asset: assets/fonts/PetrovSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/PetrovSans-ExtraLight.ttf
        - asset: assets/fonts/PetrovSans-ExtraLightItalic.ttf
        - asset: assets/fonts/PetrovSans-Light.ttf
        - asset: assets/fonts/PetrovSans-LightItalic.ttf
        - asset: assets/fonts/PetrovSans-Regular.ttf
        - asset: assets/fonts/PetrovSans-RegularItalic.ttf
        - asset: assets/fonts/PetrovSans-SemiBold.ttf
        - asset: assets/fonts/PetrovSans-SemiBoldItalic.ttf
        - asset: assets/fonts/PetrovSans-Thin.ttf
        - asset: assets/fonts/PetrovSans-ThinItalic.ttf
        

  
